### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by Head** [ballsten/eve-sso-pkce#2]
Hey, I've found your repository and it looks really cool.
I'm not sure if I'm using it as intended, maybe you could provide some example code how to use it?

**Comment by ballsten** [comment]
Hi mate, I'm currently away for a week but I'll have a crack at improving
the docs when I get back.

I just use this library in a couple of personal apps to do in browser eve
SSO.

The workflow is like this: (I'll get the method names wrong)
1. Create the object and pass in your clientid and callback url
2. Call the getUri method with the scopes needed
3. Store the returned object, you will need these values (I use vuex and
the persistedstate plugin)
4. Redirect the user to the url
5. After they complete the auth, you need to capture the callback request
and get the query parameters
6. Call the getAccessToken method with the code query param from step 5 and
the codeVerifier from step 3.
7 the returned value should be your decoded token.

**Comment by ballsten** [comment]
I've added some doco to the repository, hopefully that is helpful.

I'm planning to publish a version of this package to npm soon
